use("test")

// if specified, clear out all existing collections (except the users collection)
if (true) {
   db.attributes.deleteMany({}); 
   db.categories.deleteMany({}); 
   db.inventoryItems.deleteMany({}); 
   db.itemDefinitions.deleteMany({}); 
   db.logs.deleteMany({}); 
}

// CATEGORIES

// creates 8 categoryId variables
for (let i = 1; i <= 8; i++) {
  this[`categoryId${i}`] = ObjectId();
}

db.categories.insertMany([
    {
        "_id": categoryId1,
        "name": "Clothing"
    },
    {
        "_id": categoryId2,
        "name": "Toiletries"
    },
    {
        "_id": categoryId3,
        "name": "Furniture"
    },
    {
        "_id": categoryId4,
        "name": "Large Appliances"
    },
    {
        "_id": categoryId5,
        "name": "Small Appliances"
    },
    {
        "_id": categoryId6,
        "name": "Administrative Supplies"
    },
    {
        "_id": categoryId7,
        "name": "Linens"
    },
    {
        "_id": categoryId8,
        "name": "Cleaning Supplies"
    }
]);


// ATTRIBUTES

// creates 15 attributeId variables
for (let i = 0; i <= 15; i++) {
  this[`attributeId${i}`] = ObjectId();
}

const color1 = "#ebebeb";
const color2 = "#c7dbda";
const color3 = "#e2f0cb";
const color4 = "#55cbcd";
const color5 = "#143f46";
const color6 = "#ff6961";

db.attributes.insertMany([
    {
        "_id": attributeId1,
        "name": "Top Size",
        "possibleValues": ["Small", "Medium", "Large", "Extra-Large"],
        "color": color1
    },
    {
        "_id": attributeId2,
        "name": "Shirt Type",
        "possibleValues": ["Short-Sleeve", "Long-Sleeve"],
        "color": color2
    },
    {
        "_id": attributeId3,
        "name": "Pants Length",
        "possibleValues": ["Shorts", "Long Pants"],
        "color": color3
    },
    {
        "_id": attributeId4,
        "name": "Pants Size",
        "possibleValues": "text",
        "color": color4
    },
    {
        "_id": attributeId5,
        "name": "Shoe Size",
        "possibleValues": "number",
        "color": color5
    },
    {
        "_id": attributeId6,
        "name": "Shoe Type",
        "possibleValues": "text",
        "color": color6
    },
    {
        "_id": attributeId7,
        "name": "Bra Size",
        "possibleValues": "text",
        "color": color1
    },
    {
        "_id": attributeId8,
        "name": "Toiletry Size",
        "possibleValues": "number",
        "color": color2
    },
    {
        "_id": attributeId9,
        "name": "Brand",
        "possibleValues": "text",
        "color": color3
    },
    {
        "_id": attributeId10,
        "name": "Type",
        "possibleValues": "text",
        "color": color4
    },
    {
        "_id": attributeId11,
        "name": "Oven Type",
        "possibleValues": ["Electric", "Gas"],
        "color": color5
    },
    {
        "_id": attributeId15,
        "name": "Serial Number",
        "possibleValues": "text",
        "color": color6
    },
    {
        "_id": attributeId12,
        "name": "Value",
        "possibleValues": "number",
        "color": color1
    },
    {
        "_id": attributeId13,
        "name": "Sheet Size",
        "possibleValues": ["Twin", "Twin XL", "Full", "Queen", "King"],
        "color": color2
    },
    {
        "_id": attributeId14,
        "name": "Condition",
        "possibleValues": ["New", "Used"],
        "color": color3
    },
    {
        "_id": attributeId0,
        "name": "Location",
        "possibleValues": "text",
        "color": color1
    },
]);



// ITEM DEFINITIONS

// creates 32 itemDefinitionId variables
for (let i = 1; i <= 32; i++) {
  this[`itemDefinitionId${i}`] = ObjectId();
}

db.itemDefinitions.insertMany([
    // clothing
    {
        "_id": itemDefinitionId1,
        "name": "Shirt",
        "category": categoryId1,
        "attributes": [attributeId0, attributeId1, attributeId2],
        "internal": false,
        "lowStockThreshold": 20,
        "criticalStockThreshold": 10
    },
    {
        "_id": itemDefinitionId2,
        "name": "Pants",
        "category": categoryId1,
        "attributes": [attributeId0, attributeId3, attributeId4],
        "internal": false,
        "lowStockThreshold": 15,
        "criticalStockThreshold": 10
    },
    {
        "_id": itemDefinitionId3,
        "name": "Shoes",
        "category": categoryId1,
        "attributes": [attributeId0, attributeId5, attributeId6],
        "internal": false,
        "lowStockThreshold": 5,
        "criticalStockThreshold": 2
    },
    {
        "_id": itemDefinitionId4,
        "name": "Bra",
        "category": categoryId1,
        "attributes": [attributeId0, attributeId7],
        "internal": false,
        "lowStockThreshold": 5,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId5,
        "name": "Underwear",
        "category": categoryId1,
        "attributes": [],
        "internal": false,
        "lowStockThreshold": 15,
        "criticalStockThreshold": 10
    },
    {
        "_id": itemDefinitionId6,
        "name": "Socks",
        "category": categoryId1,
        "attributes": [attributeId0],
        "internal": false,
        "lowStockThreshold": 30,
        "criticalStockThreshold": 10
    },



    // toiletries
    {
        "_id": itemDefinitionId7,
        "name": "Shampoo",
        "category": categoryId2,
        "attributes": [attributeId0, attributeId8],
        "internal": false,
        "lowStockThreshold": 30,
        "criticalStockThreshold": 10
    },
    {
        "_id": itemDefinitionId8,
        "name": "Conditioner",
        "category": categoryId2,
        "attributes": [attributeId0, attributeId8],
        "internal": false,
        "lowStockThreshold": 30,
        "criticalStockThreshold": 10
    },
    {
        "_id": itemDefinitionId9,
        "name": "Soap",
        "category": categoryId2,
        "attributes": [attributeId0],
        "internal": false,
        "lowStockThreshold": 50,
        "criticalStockThreshold": 20
    },
    {
        "_id": itemDefinitionId10,
        "name": "Body Wash",
        "category": categoryId2,
        "attributes": [attributeId0, attributeId8],
        "internal": false,
        "lowStockThreshold": 30,
        "criticalStockThreshold": 10
    },
    {
        "_id": itemDefinitionId11,
        "name": "Shaving Cream",
        "category": categoryId2,
        "attributes": [attributeId0, attributeId8],
        "internal": false,
        "lowStockThreshold": 30,
        "criticalStockThreshold": 10
    },
    {
        "_id": itemDefinitionId12,
        "name": "Razor",
        "category": categoryId2,
        "attributes": [attributeId0],
        "internal": false,
        "lowStockThreshold": 30,
        "criticalStockThreshold": 10
    },




    // furniture
    {
        "_id": itemDefinitionId13,
        "name": "Couch",
        "category": categoryId3,
        "attributes": [attributeId0, attributeId10, attributeId14],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId14,
        "name": "Table",
        "category": categoryId3,
        "attributes": [attributeId0, attributeId10, attributeId14],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId15,
        "name": "Chair",
        "category": categoryId3,
        "attributes": [attributeId0, attributeId10, attributeId14],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },



    // large appliances
    {
        "_id": itemDefinitionId16,
        "name": "Oven",
        "category": categoryId4,
        "attributes": [attributeId0, attributeId9, attributeId11, attributeId14],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId17,
        "name": "Refrigerator",
        "category": categoryId4,
        "attributes": [attributeId0, attributeId9, attributeId10, attributeId14],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId18,
        "name": "Dishwasher",
        "category": categoryId4,
        "attributes": [attributeId0, attributeId9, attributeId10, attributeId14],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },





    // small appliances
    {
        "_id": itemDefinitionId19,
        "name": "Mini Fridge",
        "category": categoryId5,
        "attributes": [attributeId0, attributeId9, attributeId10, attributeId14],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId20,
        "name": "Coffee Maker",
        "category": categoryId5,
        "attributes": [attributeId0, attributeId9, attributeId10, attributeId14],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId21,
        "name": "Toaster",
        "category": categoryId5,
        "attributes": [attributeId0, attributeId9, attributeId10, attributeId14],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId22,
        "name": "Blender",
        "category": categoryId5,
        "attributes": [attributeId0, attributeId9, attributeId10, attributeId14],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },





    // administrative supplies
    {
        "_id": itemDefinitionId23,
        "name": "Laptop",
        "category": categoryId6,
        "attributes": [attributeId0, attributeId9, attributeId12, attributeId15],
        "internal": true,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId24,
        "name": "Keyboard",
        "category": categoryId6,
        "attributes": [attributeId0, attributeId9, attributeId12, attributeId15],
        "internal": true,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId25,
        "name": "Mouse",
        "category": categoryId6,
        "attributes": [attributeId0, attributeId9, attributeId12, attributeId15],
        "internal": true,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId26,
        "name": "Monitor",
        "category": categoryId6,
        "attributes": [attributeId0, attributeId9, attributeId12, attributeId15],
        "internal": true,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },






    // no category
    {
        "_id": itemDefinitionId27,
        "name": "Jumper Cables",
        "attributes": [attributeId0],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId28,
        "name": "Vacuum Cleaner",
        "attributes": [attributeId0, attributeId9],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    


    // linens
    {
        "_id": itemDefinitionId29,
        "name": "Towel",
        "category": categoryId7,
        "attributes": [attributeId0],
        "internal": false,
        "lowStockThreshold": 5,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId30,
        "name": "Bedsheet",
        "category": categoryId7,
        "attributes": [attributeId0, attributeId13],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId31,
        "name": "Blanket",
        "category": categoryId7,
        "attributes": [attributeId0],
        "internal": false,
        "lowStockThreshold": 10,
        "criticalStockThreshold": 5
    },
    {
        "_id": itemDefinitionId32,
        "name": "Pillow",
        "category": categoryId7,
        "attributes": [attributeId0],
        "internal": false,
        "lowStockThreshold": 10,
        "criticalStockThreshold": 5
    }
]);




const userId1 = ObjectId("648283f5211c1feb5addde70");
const userId2 = ObjectId("648283f5211c1feb5addde70");
const userId3 = ObjectId("648283f5211c1feb5addde70");
const userId4 = ObjectId("648283f5211c1feb5addde70");
const userId5 = ObjectId("648283f5211c1feb5addde70");
const userId6 = ObjectId("648283f5211c1feb5addde70");
const userId7 = ObjectId("648283f5211c1feb5addde70");

// creates 115 inventoryItemId variables
for (let i = 1; i <= 115; i++) {
  this[`inventoryItemId${i}`] = ObjectId();
}


function newLocation() {
  var letter = String.fromCharCode(65 + Math.floor(Math.random() * 26));  // A random letter A-Z
  var number = Math.floor(Math.random() * 90 + 10);  // A random two-digit number
  return letter + number;
}

// INVENTORY ITEMS
db.inventoryItems.insertMany([
    // shirt
    {
        "_id": inventoryItemId1,
        "itemDefinition": itemDefinitionId1,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId1,
                "value": "Small"
            }, 
            {
                "attribute": attributeId2,
                "value": "Short-Sleeve"
            }
        ],
        "quantity": 24
    },
    {
        "_id": inventoryItemId2,
        "itemDefinition": itemDefinitionId1,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId1,
                "value": "Small"
            }, 
            {
                "attribute": attributeId2,
                "value": "Long-Sleeve"
            }
        ],
        "quantity": 26
    },
    {
        "_id": inventoryItemId3,
        "itemDefinition": itemDefinitionId1,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId1,
                "value": "Medium"
            }, 
            {
                "attribute": attributeId2,
                "value": "Long-Sleeve"
            }
        ],
        "quantity": 6
    },
    {
        "_id": inventoryItemId4,
        "itemDefinition": itemDefinitionId1,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId1,
                "value": "Large"
            },
            {
                "attribute": attributeId2,
                "value": "Long-Sleeve"
            }
            
        ],
        "quantity": 15
    },
    {
        "_id": inventoryItemId5,
        "itemDefinition": itemDefinitionId1,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId1,
                "value": "Large"
            },
            {
                "attribute": attributeId2,
                "value": "Short-Sleeve"
            }
            
        ],
        "quantity": 22
    },
    {
        "_id": inventoryItemId6,
        "itemDefinition": itemDefinitionId1,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId1,
                "value": "Extra-Large"
            }, 
            {
                "attribute": attributeId2,
                "value": "Long-Sleeve"
            }
        ],
        "quantity": 0
    },
    {
        "_id": inventoryItemId7,
        "itemDefinition": itemDefinitionId1,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId1,
                "value": "Extra-Large"
            }, 
        ],
        "quantity": 0
    },



    // pants
    {
        "_id": inventoryItemId8,
        "itemDefinition": itemDefinitionId2,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId3,
                "value": "Shorts"
            }, 
            {
                "attribute": attributeId4,
                "value": "28x30"
            }
        ],
        "quantity": 16
    },
    {
        "_id": inventoryItemId9,
        "itemDefinition": itemDefinitionId2,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId3,
                "value": "Shorts"
            }, 
            {
                "attribute": attributeId4,
                "value": "28x32"
            }
        ],
        "quantity": 21
    },
    {
        "_id": inventoryItemId10,
        "itemDefinition": itemDefinitionId2,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId3,
                "value": "Long Pants"
            }, 
            {
                "attribute": attributeId4,
                "value": "Medium"
            }
        ],
        "quantity": 3
    },
    {
        "_id": inventoryItemId11,
        "itemDefinition": itemDefinitionId2,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId3,
                "value": "Long Pants"
            }, 
            {
                "attribute": attributeId4,
                "value": "28x30"
            }
        ],
        "quantity": 3
    },
    {
        "_id": inventoryItemId12,
        "itemDefinition": itemDefinitionId2,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId3,
                "value": "Long Pants"
            }, 
            {
                "attribute": attributeId4,
                "value": "Large"
            }
        ],
        "quantity": 12
    },



    // shoes
    {
        "_id": inventoryItemId13,
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId5,
                "value": 12
            }, 
            {
                "attribute": attributeId6,
                "value": "Tennis Shoes"
            }
        ],
        "quantity": 6
    },
    {
        "_id": inventoryItemId14,
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId5,
                "value": 4
            }, 
            {
                "attribute": attributeId6,
                "value": "Tennis Shoes"
            }
        ],
        "quantity": 2
    },
    {
        "_id": inventoryItemId15,
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId5,
                "value": 7
            }, 
            {
                "attribute": attributeId6,
                "value": "Tennis Shoes"
            }
        ],
        "quantity": 3
    },
    {
        "_id": inventoryItemId16,
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId5,
                "value": 8
            }, 
            {
                "attribute": attributeId6,
                "value": "Tennis Shoes"
            }
        ],
        "quantity": 7
    },
    {
        "_id": inventoryItemId17,
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId5,
                "value": 11
            }, 
            {
                "attribute": attributeId6,
                "value": "Tennis Shoes"
            }
        ],
        "quantity": 0
    },
    {
        "_id": inventoryItemId18,
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId5,
                "value": 12.5
            }, 
            {
                "attribute": attributeId6,
                "value": "Tennis Shoes"
            }
        ],
        "quantity": 2
    },
    {
        "_id": inventoryItemId19,
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId5,
                "value": 11.5
            }, 
            {
                "attribute": attributeId6,
                "value": "Tennis Shoes"
            }
        ],
        "quantity": 0
    },
    {
        "_id": inventoryItemId20,
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId5,
                "value": 12
            }, 
            {
                "attribute": attributeId6,
                "value": "Dress Shoes"
            }
        ],
        "quantity": 6
    },
    {
        "_id": inventoryItemId21,
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId5,
                "value": 4
            }, 
            {
                "attribute": attributeId6,
                "value": "Dress Shoes"
            }
        ],
        "quantity": 2
    },
    {
        "_id": inventoryItemId22,
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId5,
                "value": 7
            }, 
            {
                "attribute": attributeId6,
                "value": "Dress Shoes"
            }
        ],
        "quantity": 3
    },
    {
        "_id": inventoryItemId23,
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId5,
                "value": 8
            }, 
            {
                "attribute": attributeId6,
                "value": "Dress Shoes"
            }
        ],
        "quantity": 7
    },
    {
        "_id": inventoryItemId24,
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId5,
                "value": 11
            }, 
            {
                "attribute": attributeId6,
                "value": "Dress Shoes"
            }
        ],
        "quantity": 0
    },
    {
        "_id": inventoryItemId25,
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId5,
                "value": 12.5
            }, 
            {
                "attribute": attributeId6,
                "value": "Dress Shoes"
            }
        ],
        "quantity": 2
    },
    {
        "_id": inventoryItemId26,
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId5,
                "value": 11.5
            }, 
            {
                "attribute": attributeId6,
                "value": "Dress Shoes"
            }
        ],
        "quantity": 0
    },
    {
        "_id": inventoryItemId27,
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId5,
                "value": 12
            }, 
            {
                "attribute": attributeId6,
                "value": "Boots"
            }
        ],
        "quantity": 6
    },
    {
        "_id": inventoryItemId28,
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId5,
                "value": 4
            }, 
            {
                "attribute": attributeId6,
                "value": "Boots"
            }
        ],
        "quantity": 2
    },
    {
        "_id": inventoryItemId29,
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId5,
                "value": 7
            }, 
            {
                "attribute": attributeId6,
                "value": "Boots"
            }
        ],
        "quantity": 3
    },
    {
        "_id": inventoryItemId30,
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId5,
                "value": 8
            }, 
            {
                "attribute": attributeId6,
                "value": "Boots"
            }
        ],
        "quantity": 7
    },
    {
        "_id": inventoryItemId31,
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId5,
                "value": 11
            }, 
            {
                "attribute": attributeId6,
                "value": "Boots"
            }
        ],
        "quantity": 0
    },
    {
        "_id": inventoryItemId32,
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId5,
                "value": 12.5
            }, 
            {
                "attribute": attributeId6,
                "value": "Boots"
            }
        ],
        "quantity": 2
    },
    {
        "_id": inventoryItemId33,
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId5,
                "value": 11.5
            }, 
            {
                "attribute": attributeId6,
                "value": "Boots"
            }
        ],
        "quantity": 0
    },

    // bra
    {
        "_id": inventoryItemId34,
        "itemDefinition": itemDefinitionId4,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId7,
                "value": "30A"
            }
        ],
        "quantity": 3
    },
    {
        "_id": inventoryItemId35,
        "itemDefinition": itemDefinitionId4,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId7,
                "value": "32B"
            }
        ],
        "quantity": 10
    },
    {
        "_id": inventoryItemId36,
        "itemDefinition": itemDefinitionId4,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId7,
                "value": "34C"
            }
        ],
        "quantity": 7
    },
    {
        "_id": inventoryItemId37,
        "itemDefinition": itemDefinitionId4,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId7,
                "value": "36D"
            }
        ],
        "quantity": 2
    },
    {
        "_id": inventoryItemId38,
        "itemDefinition": itemDefinitionId4,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId7,
                "value": "38DD"
            }
        ],
        "quantity": 0
    },
    {
        "_id": inventoryItemId39,
        "itemDefinition": itemDefinitionId4,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId7,
                "value": "40C"
            }
        ],
        "quantity": 6
    },
    {
        "_id": inventoryItemId40,
        "itemDefinition": itemDefinitionId4,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId7,
                "value": "42B"
            }
        ],
        "quantity": 4
    },
    {
        "_id": inventoryItemId41,
        "itemDefinition": itemDefinitionId4,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId7,
                "value": "44A"
            }
        ],
        "quantity": 0
    },
    {
        "_id": inventoryItemId42,
        "itemDefinition": itemDefinitionId4,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId7,
                "value": "46D"
            }
        ],
        "quantity": 8
    },
    {
        "_id": inventoryItemId43,
        "itemDefinition": itemDefinitionId4,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, 
            {
                "attribute": attributeId7,
                "value": "48DD"
            }
        ],
        "quantity": 1
    },

    // Underwear
    {
        "_id": inventoryItemId44,
        "itemDefinition": itemDefinitionId5,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, ],
        "quantity": 20
    },

    // socks
    {
        "_id": inventoryItemId45,
        "itemDefinition": itemDefinitionId6,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            }, ],
        "quantity": 50
    },








    // Toiletries
    // Shampoo
    {
        "_id": inventoryItemId46,
        "itemDefinition": itemDefinitionId7,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId8,
                "value": 16
            }
        ],
        "quantity": 20
    },
    {
        "_id": inventoryItemId47,
        "itemDefinition": itemDefinitionId7,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId8,
                "value": 32
            }
        ],
        "quantity": 12
    },
    {
        "_id": inventoryItemId48,
        "itemDefinition": itemDefinitionId7,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId8,
                "value": 8
            }
        ],
        "quantity": 5
    },
    {
        "_id": inventoryItemId49,
        "itemDefinition": itemDefinitionId7,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId8,
                "value": 12
            }
        ],
        "quantity": 8
    },
    {
        "_id": inventoryItemId50,
        "itemDefinition": itemDefinitionId7,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId8,
                "value": 24
            }
        ],
        "quantity": 10
    },

    // conditioner
    {
        "_id": inventoryItemId51,
        "itemDefinition": itemDefinitionId8,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId8,
                "value": 16
            }
        ],
        "quantity": 20
    },
    {
        "_id": inventoryItemId52,
        "itemDefinition": itemDefinitionId8,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId8,
                "value": 32
            }
        ],
        "quantity": 12
    },
    {
        "_id": inventoryItemId53,
        "itemDefinition": itemDefinitionId8,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId8,
                "value": 8
            }
        ],
        "quantity": 5
    },
    {
        "_id": inventoryItemId54,
        "itemDefinition": itemDefinitionId8,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId8,
                "value": 12
            }
        ],
        "quantity": 8
    },
    {
        "_id": inventoryItemId55,
        "itemDefinition": itemDefinitionId8,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId8,
                "value": 24
            }
        ],
        "quantity": 10
    },

    // Soap
    {
        "_id": inventoryItemId56,
        "itemDefinition": itemDefinitionId9,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },],
        "quantity": 75
    },

    {
        "_id": inventoryItemId57,
        "itemDefinition": itemDefinitionId10,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId8,
                "value": 16
            }
        ],
        "quantity": 20
    },
    {
        "_id": inventoryItemId58,
        "itemDefinition": itemDefinitionId10,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId8,
                "value": 32
            }
        ],
        "quantity": 12
    },
    {
        "_id": inventoryItemId59,
        "itemDefinition": itemDefinitionId10,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId8,
                "value": 8
            }
        ],
        "quantity": 5
    },
    {
        "_id": inventoryItemId60,
        "itemDefinition": itemDefinitionId10,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId8,
                "value": 12
            }
        ],
        "quantity": 8
    },
    {
        "_id": inventoryItemId61,
        "itemDefinition": itemDefinitionId10,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId8,
                "value": 24
            }
        ],
        "quantity": 10
    },

    // shaving cream
    {
        "_id": inventoryItemId62,
        "itemDefinition": itemDefinitionId11,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId8,
                "value": 8
            }
        ],
        "quantity": 0
    },
    {
        "_id": inventoryItemId63,
        "itemDefinition": itemDefinitionId11,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId8,
                "value": 16
            }
        ],
        "quantity": 40
    },
    {
        "_id": inventoryItemId64,
        "itemDefinition": itemDefinitionId11,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId8,
                "value": 24
            }
        ],
        "quantity": 5
    },
    {
        "_id": inventoryItemId65,
        "itemDefinition": itemDefinitionId11,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId8,
                "value": 12
            }
        ],
        "quantity": 15
    },
    {
        "_id": inventoryItemId66,
        "itemDefinition": itemDefinitionId11,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId8,
                "value": 32
            }
        ],
        "quantity": 8
    },


    // Razor
    {
        "_id": inventoryItemId67,
        "itemDefinition": itemDefinitionId12,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },],
        "quantity": 50
    }, 

    // FURNITURE
    // couch
    {
        "_id": inventoryItemId68,
        "itemDefinition": itemDefinitionId13,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId10,
                "value": "Sectional"
            },
            {
                "attribute": attributeId14,
                "value": "Used"
            }
        ],
        "quantity": 3
    },
    {
        "_id": inventoryItemId69,
        "itemDefinition": itemDefinitionId13,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId10,
                "value": "Recliner"
            },
            {
                "attribute": attributeId14,
                "value": "New"
            }
        ],
        "quantity": 2
    },

    // Table
    {
        "_id": inventoryItemId70,
        "itemDefinition": itemDefinitionId14,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId10,
                "value": "Coffee Table"
            },
            {
                "attribute": attributeId14,
                "value": "New"
            }
        ],
        "quantity": 3
    },
    {
        "_id": inventoryItemId71,
        "itemDefinition": itemDefinitionId14,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId10,
                "value": "End Table"
            },
            {
                "attribute": attributeId14,
                "value": "Used"
            }
        ],
        "quantity": 2
    },

    // Chair
    {
        "_id": inventoryItemId72,
        "itemDefinition": itemDefinitionId15,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId10,
                "value": "Dining Chair"
            },
            {
                "attribute": attributeId14,
                "value": "New"
            }
        ],
        "quantity": 4
    },
    {
        "_id": inventoryItemId73,
        "itemDefinition": itemDefinitionId15,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId10,
                "value": "Armchair"
            },
            {
                "attribute": attributeId14,
                "value": "Used"
            }
        ],
        "quantity": 1
    },

    // Oven
    {
        "_id": inventoryItemId74,
        "itemDefinition": itemDefinitionId16,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId9,
                "value": "Samsung"
            },
            {
                "attribute": attributeId11,
                "value": "Electric"
            },
            {
                "attribute": attributeId14,
                "value": "New"
            }
        ],
        "quantity": 5
    },
    {
        "_id": inventoryItemId75,
        "itemDefinition": itemDefinitionId16,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId9,
                "value": "LG"
            },
            {
                "attribute": attributeId11,
                "value": "Gas"
            },
            {
                "attribute": attributeId14,
                "value": "Used"
            }
        ],
        "quantity": 3
    },

    // Refrigerator
    {
        "_id": inventoryItemId76,
        "itemDefinition": itemDefinitionId17,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId9,
                "value": "Whirlpool"
            },
            {
                "attribute": attributeId10,
                "value": "French Door"
            },
            {
                "attribute": attributeId14,
                "value": "New"
            }
        ],
        "quantity": 2
    },
    {
        "_id": inventoryItemId77,
        "itemDefinition": itemDefinitionId17,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId9,
                "value": "GE"
            },
            {
                "attribute": attributeId10,
                "value": "Side-by-Side"
            },
            {
                "attribute": attributeId14,
                "value": "Used"
            }
        ],
        "quantity": 1
    },

    // Dishwasher
    {
        "_id": inventoryItemId78,
        "itemDefinition": itemDefinitionId18,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId9,
                "value": "Bosch"
            },
            {
                "attribute": attributeId10,
                "value": "Built-in"
            },
            {
                "attribute": attributeId14,
                "value": "New"
            }
        ],
        "quantity": 4
    },
    {
        "_id": inventoryItemId79,
        "itemDefinition": itemDefinitionId18,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId9,
                "value": "KitchenAid"
            },
            {
                "attribute": attributeId10,
                "value": "Portable"
            },
            {
                "attribute": attributeId14,
                "value": "Used"
            }
        ],
        "quantity": 2
    },

    // Mini Fridge
    {
        "_id": inventoryItemId80,
        "itemDefinition": itemDefinitionId19,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId9,
                "value": "LG"
            },
            {
                "attribute": attributeId11,
                "value": "Compact"
            },
            {
                "attribute": attributeId14,
                "value": "New"
            }
        ],
        "quantity": 10
    },
    {
        "_id": inventoryItemId81,
        "itemDefinition": itemDefinitionId19,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId9,
                "value": "Samsung"
            },
            {
                "attribute": attributeId11,
                "value": "Mini"
            },
            {
                "attribute": attributeId14,
                "value": "New"
            }
        ],
        "quantity": 5
    },
    {
        "_id": inventoryItemId82,
        "itemDefinition": itemDefinitionId19,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId9,
                "value": "Whirlpool"
            },
            {
                "attribute": attributeId11,
                "value": "Small"
            },
            {
                "attribute": attributeId14,
                "value": "Used"
            }
        ],
        "quantity": 2
    },

    // Coffee Maker
    {
        "_id": inventoryItemId83,
        "itemDefinition": itemDefinitionId20,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId9,
                "value": "Keurig"
            },
            {
                "attribute": attributeId11,
                "value": "Single Serve"},
            {
                "attribute": attributeId14,
                "value": "New"
            }
        ],
        "quantity": 8
    },
    {
        "_id": inventoryItemId84,
        "itemDefinition": itemDefinitionId20,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId9,
                "value": "Cuisinart"
            },
            {
                "attribute": attributeId11,
                "value": "Drip"
            },
            {
                "attribute": attributeId14,
                "value": "New"
            }
        ],
        "quantity": 4
    },
    {
        "_id": inventoryItemId85,
        "itemDefinition": itemDefinitionId20,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId9,
                "value": "Hamilton Beach"},
            {
                "attribute": attributeId11,
                "value": "Percolator"
            },
            {
                "attribute": attributeId14,
                "value": "Used"
            }
        ],
        "quantity": 1
    },

    // Toaster
    {
        "_id": inventoryItemId86,
        "itemDefinition": itemDefinitionId21,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId9,
                "value": "Cuisinart"
            },
            {
                "attribute": attributeId10,
                "value": "2 Slice"
            },
            {
                "attribute": attributeId14,
                "value": "New"
            }
        ],
        "quantity": 10
    },
    {
        "_id": inventoryItemId87,
        "itemDefinition": itemDefinitionId21,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId9,
                "value": "KitchenAid"
            },
            {
                "attribute": attributeId10,
                "value": "4 Slice"
            },
            {
                "attribute": attributeId14,
                "value": "New"
            }
        ],
        "quantity": 5
    },
    {
        "_id": inventoryItemId88,
        "itemDefinition": itemDefinitionId21,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId9,
                "value": "Black & Decker"
            },
            {
                "attribute": attributeId10,
                "value": "Toaster Oven"
            },
            {
                "attribute": attributeId14,
                "value": "Used"
            }
        ],
        "quantity": 2
    },

    // Blender
    {
        "_id": inventoryItemId89,
        "itemDefinition": itemDefinitionId22,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId9,
                "value": "Ninja"
            },
            {
                "attribute": attributeId10,
                "value": "Countertop"
            },
            {
                "attribute": attributeId14,
                "value": "New"
            }
        ],
        "quantity": 8
    },
    {
        "_id": inventoryItemId90,
        "itemDefinition": itemDefinitionId22,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId9,
                "value": "Vitamix"
            },
            {
                "attribute": attributeId10,
                "value": "Personal"
            },
            {
                "attribute": attributeId14,
                "value": "New"
            }
        ],
        "quantity": 4
    },
    {
        "_id": inventoryItemId91,
        "itemDefinition": itemDefinitionId22,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId9,
                "value": "Oster"
            },
            {
                "attribute": attributeId10,
                "value": "Handheld"
            },
            {
                "attribute": attributeId14,
                "value": "Used"
            }
        ],
        "quantity": 1
    },


    // ADMINISTRATIVE SUPPLIES

    //Laptop
    {
        "_id": inventoryItemId92,
        "itemDefinition": itemDefinitionId23,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId9,
                "value": "Dell"
            },
            {
                "attribute": attributeId12,
                "value": 1300
            },
            {
                "attribute": attributeId15,
                "value": "ABCD1234"
            }
        ],
        "quantity": 1,
        "assignee": userId1
    },
    {
        "_id": inventoryItemId93,
        "itemDefinition": itemDefinitionId23,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {"attribute": attributeId9, "value": "Lenovo"},
            {"attribute": attributeId12, "value": 1200},
            {"attribute": attributeId15, "value": "EFGH5678"}
        ],
        "quantity": 1,
        "assignee": userId2
    },
    {
        "_id": inventoryItemId94,
        "itemDefinition": itemDefinitionId23,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {"attribute": attributeId9, "value": "HP"},
            {"attribute": attributeId12, "value": 1800},
            {"attribute": attributeId15, "value": "IJKL9012"}
        ],
        "quantity": 1,
        "assignee": userId3
    },

    //Keyboard
    {
        "_id": inventoryItemId95,
        "itemDefinition": itemDefinitionId24,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {"attribute": attributeId9, "value": "Dell"},
            {"attribute": attributeId12, "value": 50},
            {"attribute": attributeId15, "value": "MNOP3456"}
        ],
        "quantity": 1,
        "assignee": userId1
    },
    {
        "_id": inventoryItemId96,
        "itemDefinition": itemDefinitionId24,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {"attribute": attributeId9, "value": "Lenovo"},
            {"attribute": attributeId12, "value": 40},
            {"attribute": attributeId15, "value": "QRST7890"}
        ],
        "quantity": 1,
        "assignee": userId2
    },
    {
        "_id": inventoryItemId97,
        "itemDefinition": itemDefinitionId24,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {"attribute": attributeId9, "value": "HP"},
            {"attribute": attributeId12, "value": 60},
            {"attribute": attributeId15, "value": "UVWX1234"}
        ],
        "quantity": 1,
        "assignee": userId3
    },

    // Mouse
    {
        "_id": inventoryItemId98,
        "itemDefinition": itemDefinitionId25,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {"attribute": attributeId9, "value": "Dell"},
            {"attribute": attributeId12, "value": 50},
            {"attribute": attributeId15, "value": "ABCD1234"}
        ],
        "quantity": 1,
        "assignee": userId1
    },
    {
        "_id": inventoryItemId99,
        "itemDefinition": itemDefinitionId25,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {"attribute": attributeId9, "value": "Lenovo"},
            {"attribute": attributeId12, "value": 40},
            {"attribute": attributeId15, "value": "EFGH5678"}
        ],
        "quantity": 1,
        "assignee": userId2
    },
    {
        "_id": inventoryItemId100,
        "itemDefinition": itemDefinitionId25,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {"attribute": attributeId9, "value": "HP"},
            {"attribute": attributeId12, "value": 60},
            {"attribute": attributeId15, "value": "IJKL9012"}
        ],
        "quantity": 1,
        "assignee": userId3
    },

    // Monitor
    {
        "_id": inventoryItemId101,
        "itemDefinition": itemDefinitionId26,
        "attributes": [
            {"attribute": attributeId9, "value": "Dell"},
            {"attribute": attributeId12, "value": 1500},
            {"attribute": attributeId15, "value": "MNOP3456"}
        ],
        "quantity": 1,
        "assignee": userId1
    },
    {
        "_id": inventoryItemId102,
        "itemDefinition": itemDefinitionId26,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {"attribute": attributeId9, "value": "Lenovo"},
            {"attribute": attributeId12, "value": 1200},
            {"attribute": attributeId15, "value": "QRST7890"}
        ],
        "quantity": 1,
        "assignee": userId2
    },
    {
        "_id": inventoryItemId103,
        "itemDefinition": itemDefinitionId26,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {"attribute": attributeId9, "value": "HP"},
            {"attribute": attributeId12, "value": 1800},
            {"attribute": attributeId15, "value": "UVWX1234"}
        ],
        "quantity": 1,
        "assignee": userId3
    },


    // NO CATEGORY

    // Jumper Cables
    {
        "_id": inventoryItemId104,
        "itemDefinition": itemDefinitionId27,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },],
        "quantity": 10
    },

    // Vacuum Cleaner
    {
        "_id": inventoryItemId105,
        "itemDefinition": itemDefinitionId28,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId9,
                "value": "Dyson"
            }
        ],
        "quantity": 2
    },
    {
        "_id": inventoryItemId106,
        "itemDefinition": itemDefinitionId28,
        "attributes": [
            {
                "attribute": attributeId9,
                "value": "Hoover"
            }
        ],
        "quantity": 1
    },
    {
        "_id": inventoryItemId107,
        "itemDefinition": itemDefinitionId28,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId9,
                "value": "Shark"
            }
        ],
        "quantity": 3
    },

    // Towel
    {
        "_id": inventoryItemId108,
        "itemDefinition": itemDefinitionId29,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },],
        "quantity": 1
    },

    // Bedsheet
    {
        "_id": inventoryItemId109,
        "itemDefinition": itemDefinitionId30,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId13,
                "value": "Twin"
            }
        ],
        "quantity": 3
    },
    {
        "_id": inventoryItemId110,
        "itemDefinition": itemDefinitionId30,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId13,
                "value": "Twin XL"
            }
        ],
        "quantity": 7
    },
    {
        "_id": inventoryItemId111,
        "itemDefinition": itemDefinitionId30,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId13,
                "value": "Full"
            }
        ],
        "quantity": 2
    },
    {
        "_id": inventoryItemId112,
        "itemDefinition": itemDefinitionId30,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
            "attribute": attributeId13,
            "value": "Queen"
            }
        ],
        "quantity": 0
    },
    {
        "_id": inventoryItemId113,
        "itemDefinition": itemDefinitionId30,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },
            {
                "attribute": attributeId13,
                "value": "King"
            }
        ],
        "quantity": 1
    },

    // Blanket
    {
        "_id": inventoryItemId114,
        "itemDefinition": itemDefinitionId31,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },],
        "quantity": 15
    },

    // Pillow
    {
        "_id": inventoryItemId115,
        "itemDefinition": itemDefinitionId32,
        "attributes": [
            {
                "attribute": attributeId0,
                "value": newLocation()
            },],
        "quantity": 2
    }
])


// LOGS -- this creates 500 randomly generated documents (thanks chatgpt!)
var userIds = [];
for (var i = 1; i <= 7; i++) {
    userIds.push('userId' + i);
}

var inventoryItemIds = [];
for (var i = 1; i <= 115; i++) {
    inventoryItemIds.push('inventoryItemId' + i);
}

var documents = [];
for (var i = 0; i < 500; i++) {
    var staff = userIds[Math.floor(Math.random() * userIds.length)];
    var item = inventoryItemIds[Math.floor(Math.random() * inventoryItemIds.length)];
    var quantityDelta = Math.floor(Math.random() * 100) - 50 || 1;
    var date = new Date(new Date() - Math.floor(Math.random() * 63072000000)); // 2 years in milliseconds
    var document = {
        _id: ObjectId(),
        staff: this[staff],
        item: this[item],
        quantityDelta: quantityDelta,
        date: date
    };
    documents.push(document);
}

db.logs.insertMany(documents);

