use test;

// CATEGORIES
const categoryId1 = ObjectId();
const categoryId2 = ObjectId();
const categoryId3 = ObjectId();
const categoryId4 = ObjectId();
const categoryId5 = ObjectId();
const categoryId6 = ObjectId();
const categoryId7 = ObjectId();
const categoryId8 = ObjectId();

db.categories.insertMany(
    {
        "_id": categoryId1,
        "name": "Clothing"
    },
    {
        "_id": categoryId2,
        "name": "Toiletries"
    },
    {
        "_id": categoryId3,
        "name": "Furniture"
    },
    {
        "_id": categoryId4,
        "name": "Large Appliances"
    },
    {
        "_id": categoryId5,
        "name": "Small Appliances"
    },
    {
        "_id": categoryId6,
        "name": "Administrative Supplies"
    },
    {
        "_id": categoryId7,
        "name": "Linens"
    }
    {
        "_id": categoryId8,
        "name": "Cleaning Supplies"
    },
);


// ATTRIBUTES
const attributeId1 = ObjectId();
const attributeId2 = ObjectId();
const attributeId3 = ObjectId();
const attributeId4 = ObjectId();
const attributeId5 = ObjectId();
const attributeId6 = ObjectId();
const attributeId7 = ObjectId();
const attributeId8 = ObjectId();
const attributeId9 = ObjectId();
const attributeId10 = ObjectId();
const attributeId11 = ObjectId();
const attributeId12 = ObjectId();
const attributeId13 = ObjectId();
const attributeId14 = ObjectId();
const defaultColor = "#ebebeb";

db.attributes.insertMany(
    {
        "_id": attributeId1,
        "name": "Top Size",
        "possibleValues": ["Small", "Medium", "Large", "Extra-Large"],
        "color": defaultColor
    },
    {
        "_id": attributeId2,
        "name": "Shirt Type",
        "possibleValues": ["Short-Sleeve", "Long-Sleeve"],
        "color": defaultColor
    },
    {
        "_id": attributeId3,
        "name": "Pants Length",
        "possibleValues": ["Shorts", "Long Pants"],
        "color": defaultColor
    },
    {
        "_id": attributeId4,
        "name": "Pants Size",
        "possibleValues": "text",
        "color": defaultColor
    },
    {
        "_id": attributeId5,
        "name": "Shoe Size",
        "possibleValues": "number",
        "color": defaultColor
    },
    {
        "_id": attributeId6,
        "name": "Shoe Type",
        "possibleValues": "text",
        "color": defaultColor
    },
    {
        "_id": attributeId7,
        "name": "Bra Size",
        "possibleValues": "text",
        "color": defaultColor
    },
    {
        "_id": attributeId8,
        "name": "Toiletry Size",
        "possibleValues": "number",
        "color": defaultColor
    },
    {
        "_id": attributeId9,
        "name": "Brand",
        "possibleValues": "text",
        "color": defaultColor
    },
    {
        "_id": attributeId10,
        "name": "Type",
        "possibleValues": "text",
        "color": defaultColor
    },
    {
        "_id": attributeId11,
        "name": "Oven Type",
        "possibleValues": ["Electric", "Gas"],
        "color": defaultColor
    },
    {
        "_id": attributeId12,
        "name": "Value",
        "possibleValues": "number",
        "color": defaultColor
    },
    {
        "_id": attributeId13,
        "name": "Sheet Size",
        "possibleValues": ["Twin", "Twin XL", "Full", "Queen", "King"],
        "color": defaultColor
    },
    {
        "_id": attributeId14,
        "name": "Condition",
        "possibleValues": ["New", "Used"],
        "color": defaultColor
    },
);



// ITEM DEFINITIONS
const itemDefinitionId1 = ObjectId();
const itemDefinitionId2 = ObjectId();
const itemDefinitionId3 = ObjectId();
const itemDefinitionId4 = ObjectId();
const itemDefinitionId5 = ObjectId();
const itemDefinitionId6 = ObjectId();
const itemDefinitionId7 = ObjectId();
const itemDefinitionId8 = ObjectId();
const itemDefinitionId9 = ObjectId();
const itemDefinitionId10 = ObjectId();
const itemDefinitionId12 = ObjectId();
const itemDefinitionId13 = ObjectId();
const itemDefinitionId14 = ObjectId();
const itemDefinitionId15 = ObjectId();
const itemDefinitionId16 = ObjectId();
const itemDefinitionId17 = ObjectId();
const itemDefinitionId18 = ObjectId();
const itemDefinitionId19 = ObjectId();
const itemDefinitionId20 = ObjectId();
const itemDefinitionId21 = ObjectId();
const itemDefinitionId22 = ObjectId();
const itemDefinitionId23 = ObjectId();
const itemDefinitionId24 = ObjectId();
const itemDefinitionId25 = ObjectId();
const itemDefinitionId26 = ObjectId();
const itemDefinitionId27 = ObjectId();
const itemDefinitionId28 = ObjectId();
const itemDefinitionId29 = ObjectId();
const itemDefinitionId30 = ObjectId();
const itemDefinitionId31 = ObjectId();
const itemDefinitionId32 = ObjectId();

db.itemDefinitions.insertMany(
    // clothing
    {
        "_id": itemDefinitionId1,
        "name": "Shirt",
        "category": categoryId1,
        "attributes": [attributeId1, attributeId2],
        "internal": false,
        "lowStockThreshold": 20,
        "criticalStockThreshold": 10
    },
    {
        "_id": itemDefinitionId2,
        "name": "Pants",
        "category": categoryId1,
        "attributes": [attributeId3, attributeId4],
        "internal": false,
        "lowStockThreshold": 15,
        "criticalStockThreshold": 10
    },
    {
        "_id": itemDefinitionId3,
        "name": "Shoes",
        "category": categoryId1,
        "attributes": [attributeId5, attributeId6],
        "internal": false,
        "lowStockThreshold": 5,
        "criticalStockThreshold": 2
    },
    {
        "_id": itemDefinitionId4,
        "name": "Bra",
        "category": categoryId1,
        "attributes": [attributeId7],
        "internal": false,
        "lowStockThreshold": 5,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId5,
        "name": "Underwear",
        "category": categoryId1,
        "attributes": [],
        "internal": false,
        "lowStockThreshold": 15,
        "criticalStockThreshold": 10
    },
    {
        "_id": itemDefinitionId6,
        "name": "Socks",
        "category": categoryId1,
        "attributes": [],
        "internal": false,
        "lowStockThreshold": 30,
        "criticalStockThreshold": 10
    },



    // toiletries
    {
        "_id": itemDefinitionId7,
        "name": "Shampoo",
        "category": categoryId2,
        "attributes": [attributeId8],
        "internal": false,
        "lowStockThreshold": 30,
        "criticalStockThreshold": 10
    },
    {
        "_id": itemDefinitionId8,
        "name": "Conditioner",
        "category": categoryId2,
        "attributes": [attributeId8],
        "internal": false,
        "lowStockThreshold": 30,
        "criticalStockThreshold": 10
    },
    {
        "_id": itemDefinitionId9,
        "name": "Soap",
        "category": categoryId2,
        "attributes": [],
        "internal": false,
        "lowStockThreshold": 50,
        "criticalStockThreshold": 20
    },
    {
        "_id": itemDefinitionId10,
        "name": "Body Wash",
        "category": categoryId2,
        "attributes": [attributeId8],
        "internal": false,
        "lowStockThreshold": 30,
        "criticalStockThreshold": 10
    },
    {
        "_id": itemDefinitionId11,
        "name": "Shaving Cream",
        "category": categoryId2,
        "attributes": [attributeId8],
        "internal": false,
        "lowStockThreshold": 30,
        "criticalStockThreshold": 10
    },
    {
        "_id": itemDefinitionId12,
        "name": "Razor",
        "category": categoryId2,
        "attributes": [],
        "internal": false,
        "lowStockThreshold": 30,
        "criticalStockThreshold": 10
    },




    // furniture
    {
        "_id": itemDefinitionId13,
        "name": "Couch",
        "category": categoryId3,
        "attributes": [attributeId10, attributeId14],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId14,
        "name": "Table",
        "category": categoryId3,
        "attributes": [attributeId10, attributeId14],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId15,
        "name": "Chair",
        "category": categoryId3,
        "attributes": [attributeId10, attributeId14],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },



    // large appliances
    {
        "_id": itemDefinitionId16,
        "name": "Oven",
        "category": categoryId4,
        "attributes": [attributeId9, attributeId11, attributeId14],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId17,
        "name": "Refrigerator",
        "category": categoryId4,
        "attributes": [attributeId9, attributeId11, attributeId14],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId18,
        "name": "Dishwasher",
        "category": categoryId4,
        "attributes": [attributeId9, attributeId11, attributeId14],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },





    // small appliances
    {
        "_id": itemDefinitionId19,
        "name": "Mini Fridge",
        "category": categoryId5,
        "attributes": [attributeId9, attributeId11, attributeId14],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId20,
        "name": "Coffee Maker",
        "category": categoryId5,
        "attributes": [attributeId9, attributeId11, attributeId14],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId21,
        "name": "Toaster",
        "category": categoryId5,
        "attributes": [attributeId9, attributeId11, attributeId14],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId22,
        "name": "Blender",
        "category": categoryId5,
        "attributes": [attributeId9, attributeId11, attributeId14],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },





    // administrative supplies
    {
        "_id": itemDefinitionId23,
        "name": "Laptop",
        "category": categoryId6,
        "attributes": [attributeId9, attributeId12],
        "internal": true,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId24,
        "name": "Keyboard",
        "category": categoryId6,
        "attributes": [attributeId9, attributeId12],
        "internal": true,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId25,
        "name": "Mouse",
        "category": categoryId6,
        "attributes": [attributeId9, attributeId12],
        "internal": true,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId26,
        "name": "Monitor",
        "category": categoryId6,
        "attributes": [attributeId9, attributeId12],
        "internal": true,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },






    // no category
    {
        "_id": itemDefinitionId27,
        "name": "Jumper Cables",
        "attributes": [],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId28,
        "name": "Vacuum Cleaner",
        "attributes": [attributeId9],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    


    // linens
    {
        "_id": itemDefinitionId29,
        "name": "Towel",
        "category": categoryId7,
        "attributes": [],
        "internal": false,
        "lowStockThreshold": 5,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId30,
        "name": "Bedsheet",
        "category": categoryId7,
        "attributes": [attributeId13],
        "internal": false,
        "lowStockThreshold": 0,
        "criticalStockThreshold": 0
    },
    {
        "_id": itemDefinitionId31,
        "name": "Blanket",
        "category": categoryId7,
        "attributes": [],
        "internal": false,
        "lowStockThreshold": 10,
        "criticalStockThreshold": 5
    },
    {
        "_id": itemDefinitionId32,
        "name": "Pillow",
        "category": categoryId7,
        "attributes": [],
        "internal": false,
        "lowStockThreshold": 10,
        "criticalStockThreshold": 5
    }
);







// INVENTORY ITEMS
db.inventoryItems.insertMany(
    // shirt
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId1,
        "attributes": [
            {
                "attribute": attributeId1,
                "value": "Small"
            }, 
            {
                "attribute": attributeId2,
                "value": "Short-Sleeve"
            }
        ],
        "quantity": 24,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId1,
        "attributes": [
            {
                "attribute": attributeId1,
                "value": "Small"
            }, 
            {
                "attribute": attributeId2,
                "value": "Long-Sleeve"
            }
        ],
        "quantity": 26,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId1,
        "attributes": [
            {
                "attribute": attributeId1,
                "value": "Medium"
            }, 
            {
                "attribute": attributeId2,
                "value": "Long-Sleeve"
            }
        ],
        "quantity": 6,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId1,
        "attributes": [
            {
                "attribute": attributeId1,
                "value": "Large"
            },
            {
                "attribute": attributeId2,
                "value": "Long-Sleeve"
            }
            
        ],
        "quantity": 15,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId1,
        "attributes": [
            {
                "attribute": attributeId1,
                "value": "Large"
            },
            {
                "attribute": attributeId2,
                "value": "Short-Sleeve"
            }
            
        ],
        "quantity": 22,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId1,
        "attributes": [
            {
                "attribute": attributeId1,
                "value": "Extra-Large"
            }, 
            {
                "attribute": attributeId2,
                "value": "Long-Sleeve"
            }
        ],
        "quantity": 0,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId1,
        "attributes": [
            {
                "attribute": attributeId1,
                "value": "Extra-Large"
            }, 
        ],
        "quantity": 0,
    },



    // pants
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId2,
        "attributes": [
            {
                "attribute": attributeId3,
                "value": "Shorts"
            }, 
            {
                "attribute": attributeId4,
                "value": "28x30"
            }
        ],
        "quantity": 16,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId2,
        "attributes": [
            {
                "attribute": attributeId3,
                "value": "Shorts"
            }, 
            {
                "attribute": attributeId4,
                "value": "28x32"
            }
        ],
        "quantity": 21,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId2,
        "attributes": [
            {
                "attribute": attributeId3,
                "value": "Long Pants"
            }, 
            {
                "attribute": attributeId4,
                "value": "Medium"
            }
        ],
        "quantity": 3,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId2,
        "attributes": [
            {
                "attribute": attributeId3,
                "value": "Long Pants"
            }, 
            {
                "attribute": attributeId4,
                "value": "28x30"
            }
        ],
        "quantity": 3,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId2,
        "attributes": [
            {
                "attribute": attributeId3,
                "value": "Long Pants"
            }, 
            {
                "attribute": attributeId4,
                "value": "Large"
            }
        ],
        "quantity": 12,
    },



    // shoes
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId5,
                "value": "12"
            }, 
            {
                "attribute": attributeId6,
                "value": "Tennis Shoes"
            }
        ],
        "quantity": 6,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId5,
                "value": "4"
            }, 
            {
                "attribute": attributeId6,
                "value": "Tennis Shoes"
            }
        ],
        "quantity": 2,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId5,
                "value": "7"
            }, 
            {
                "attribute": attributeId6,
                "value": "Tennis Shoes"
            }
        ],
        "quantity": 3,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId5,
                "value": "8"
            }, 
            {
                "attribute": attributeId6,
                "value": "Tennis Shoes"
            }
        ],
        "quantity": 7,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId5,
                "value": "11"
            }, 
            {
                "attribute": attributeId6,
                "value": "Tennis Shoes"
            }
        ],
        "quantity": 0,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId5,
                "value": "12.5"
            }, 
            {
                "attribute": attributeId6,
                "value": "Tennis Shoes"
            }
        ],
        "quantity": 2,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId5,
                "value": "11.5"
            }, 
            {
                "attribute": attributeId6,
                "value": "Tennis Shoes"
            }
        ],
        "quantity": 0,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId5,
                "value": "12"
            }, 
            {
                "attribute": attributeId6,
                "value": "Dress Shoes"
            }
        ],
        "quantity": 6,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId5,
                "value": "4"
            }, 
            {
                "attribute": attributeId6,
                "value": "Dress Shoes"
            }
        ],
        "quantity": 2,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId5,
                "value": "7"
            }, 
            {
                "attribute": attributeId6,
                "value": "Dress Shoes"
            }
        ],
        "quantity": 3,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId5,
                "value": "8"
            }, 
            {
                "attribute": attributeId6,
                "value": "Dress Shoes"
            }
        ],
        "quantity": 7,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId5,
                "value": "11"
            }, 
            {
                "attribute": attributeId6,
                "value": "Dress Shoes"
            }
        ],
        "quantity": 0,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId5,
                "value": "12.5"
            }, 
            {
                "attribute": attributeId6,
                "value": "Dress Shoes"
            }
        ],
        "quantity": 2,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId5,
                "value": "11.5"
            }, 
            {
                "attribute": attributeId6,
                "value": "Dress Shoes"
            }
        ],
        "quantity": 0,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId5,
                "value": "12"
            }, 
            {
                "attribute": attributeId6,
                "value": "Boots"
            }
        ],
        "quantity": 6,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId5,
                "value": "4"
            }, 
            {
                "attribute": attributeId6,
                "value": "Boots"
            }
        ],
        "quantity": 2,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId5,
                "value": "7"
            }, 
            {
                "attribute": attributeId6,
                "value": "Boots"
            }
        ],
        "quantity": 3,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId5,
                "value": "8"
            }, 
            {
                "attribute": attributeId6,
                "value": "Boots"
            }
        ],
        "quantity": 7,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId5,
                "value": "11"
            }, 
            {
                "attribute": attributeId6,
                "value": "Boots"
            }
        ],
        "quantity": 0,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId5,
                "value": "12.5"
            }, 
            {
                "attribute": attributeId6,
                "value": "Boots"
            }
        ],
        "quantity": 2,
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId3,
        "attributes": [
            {
                "attribute": attributeId5,
                "value": "11.5"
            }, 
            {
                "attribute": attributeId6,
                "value": "Boots"
            }
        ],
        "quantity": 0,
    },

    // bra
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId4,
        "attributes": [
            {
                "attribute": attributeId7,
                "value": "30A"
            }
        ],
        "quantity": 3
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId4,
        "attributes": [
            {
                "attribute": attributeId7,
                "value": "32B"
            }
        ],
        "quantity": 10
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId4,
        "attributes": [
            {
                "attribute": attributeId7,
                "value": "34C"
            }
        ],
        "quantity": 7
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId4,
        "attributes": [
            {
                "attribute": attributeId7,
                "value": "36D"
            }
        ],
        "quantity": 2
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId4,
        "attributes": [
            {
                "attribute": attributeId7,
                "value": "38DD"
            }
        ],
        "quantity": 0
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId4,
        "attributes": [
            {
                "attribute": attributeId7,
                "value": "40C"
            }
        ],
        "quantity": 6
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId4,
        "attributes": [
            {
                "attribute": attributeId7,
                "value": "42B"
            }
        ],
        "quantity": 4
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId4,
        "attributes": [
            {
                "attribute": attributeId7,
                "value": "44A"
            }
        ],
        "quantity": 0
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId4,
        "attributes": [
            {
                "attribute": attributeId7,
                "value": "46D"
            }
        ],
        "quantity": 8
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId4,
        "attributes": [
            {
                "attribute": attributeId7,
                "value": "48DD"
            }
        ],
        "quantity": 1
    },

    // Underwear
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId5,
        "attributes": [],
        "quantity": 20
    },

    // socks
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId6,
        "attributes": [],
        "quantity": 50
    },








    // Toiletries
    // Shampoo
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId7,
        "attributes": [
            {
                "attribute": attributeId8,
                "value": "16 oz"
            }
        ],
        "quantity": 20
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId7,
        "attributes": [
            {
                "attribute": attributeId8,
                "value": "32 oz"
            }
        ],
        "quantity": 12
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId7,
        "attributes": [
            {
                "attribute": attributeId8,
                "value": "8 oz"
            }
        ],
        "quantity": 5
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId7,
        "attributes": [
            {
                "attribute": attributeId8,
                "value": "12 oz"
            }
        ],
        "quantity": 8
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId7,
        "attributes": [
            {
                "attribute": attributeId8,
                "value": "24 oz"
            }
        ],
        "quantity": 10
    },

    // conditioner
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId8,
        "attributes": [
            {
                "attribute": attributeId8,
                "value": "16 oz"
            }
        ],
        "quantity": 20
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId8,
        "attributes": [
            {
                "attribute": attributeId8,
                "value": "32 oz"
            }
        ],
        "quantity": 12
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId8,
        "attributes": [
            {
                "attribute": attributeId8,
                "value": "8 oz"
            }
        ],
        "quantity": 5
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId8,
        "attributes": [
            {
                "attribute": attributeId8,
                "value": "12 oz"
            }
        ],
        "quantity": 8
    },
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId8,
        "attributes": [
            {
                "attribute": attributeId8,
                "value": "24 oz"
            }
        ],
        "quantity": 10
    },

    // Soap
    {
        "_id": ObjectId(),
        "itemDefinition": itemDefinitionId9,
        "attributes": [],
        "quantity": 75
    }
)